modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="campfire_overhaul"
version="2.0.0"
displayName="Campfire Overhaul+"
authors="ZanderMeister (ported by AriAja17)"
description='''
    A mod that overhauls campfire mechanics to enhance immersion and usefulness.
    Ported to 1.20.1 & 1.21.x
    '''

[[dependencies.campfire_overhaul]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.campfire_overhaul]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"